import localFont from "next/font/local";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

const noto = localFont({
  src: "./notoSans.woff2",
  display: "swap",
});
export const metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
